### ISSUE TITLE
No transaction error

### ISSUE THREAD

**Issue by arnoudius** [dewi-alliance/helium-etl-lite#13]
Hi, 

First of all, nice initiative / tool!

I'm having an issue getting it to run. I followed the quick start guide and blockchain-node seems to be syncing. Once I run helium-etl-lite I keep getting following error (ever after syncing for 24+ hours) ->

```
target/release/helium_etl_lite start

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NodeError("No transaction: <<\"Wh40ejvFhSY65XO5lo7sfZuIdNIUSpCC2wD4SjA3mPA\">>", -100)', /home/arnout/repos/helium-etl-lite/src/follower.rs:194:79
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: helium_etl_lite::main::{{closure}}::run::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: tokio::park::thread::CachedParkThread::block_on
   6: tokio::runtime::thread_pool::ThreadPool::block_on
   7: helium_etl_lite::main
note: Some details are omitted, run
```

```
Oct 17 15:46:47.139 INFO hello!
Oct 17 15:46:47.154 INFO no follower_info data
Oct 17 15:46:47.154 INFO Scanning blocks by epoch to get first block on node.
Oct 17 15:46:49.543 INFO Getting start_epoch from block 1048423
Oct 17 15:46:51.516 INFO Getting start_epoch from block 1048389
Oct 17 15:46:53.110 INFO Getting start_epoch from block 1048351
Oct 17 15:46:54.575 INFO Getting start_epoch from block 1048316
Oct 17 15:46:55.962 INFO Getting start_epoch from block 1048283
Oct 17 15:46:57.397 INFO Getting start_epoch from block 1048250
Oct 17 15:46:59.091 INFO Getting start_epoch from block 1048217
... some 60 more blocks until it panics
```

Do you maybe know what might be causing this / how to fix it?

**Comment by olb1ue** [comment]
Thanks for reporting this. I have a theory of what's happening here. Do you mind showing me what's in your `sys.config` file for your blockchain-node?

**Comment by arnoudius** [comment]
Thanks for having a look. I've attached my blockchain-node's sys.config file. 

[sys.config.txt](https://github.com/dewi-alliance/helium-etl-lite/files/7367796/sys.config.txt)

**Comment by olb1ue** [comment]
didn't mean to close this yet!

**Comment by arnoudius** [comment]
I just tried it out and it seems be working now. Thanks!
